-- Jawa EdTech production Supabase schema
-- Run this in Supabase SQL Editor after creating your project.

create extension if not exists "pgcrypto";

create table if not exists public.students (
  id uuid primary key default gen_random_uuid(),
  full_name text not null,
  email text not null unique,
  phone text,
  college_name text,
  degree text,
  year_of_study text,
  city text,
  state text,
  course_interest text,
  created_at timestamptz not null default now(),
  last_login timestamptz
);

create table if not exists public.admin_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  full_name text,
  role text not null default 'admin',
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.login_activity (
  id bigint generated by default as identity primary key,
  student_id uuid references public.students(id) on delete set null,
  login_time timestamptz not null default now(),
  logout_time timestamptz,
  ip_address text,
  device_type text,
  browser text,
  location text
);

create table if not exists public.course_applications (
  id bigint generated by default as identity primary key,
  student_id uuid references public.students(id) on delete set null,
  course_name text not null,
  application_date timestamptz not null default now(),
  status text not null default 'new',
  remarks text
);

create table if not exists public.internship_applications (
  id bigint generated by default as identity primary key,
  student_id uuid references public.students(id) on delete set null,
  internship_name text not null,
  application_date timestamptz not null default now(),
  status text not null default 'new',
  remarks text
);

create table if not exists public.career_counselling_requests (
  id bigint generated by default as identity primary key,
  student_id uuid references public.students(id) on delete set null,
  name text not null,
  email text not null,
  phone text,
  course_interest text,
  message text,
  request_date timestamptz not null default now(),
  status text not null default 'new'
);

create table if not exists public.contact_us (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  phone text,
  message text,
  submitted_at timestamptz not null default now()
);

create table if not exists public.newsletter_subscribers (
  id bigint generated by default as identity primary key,
  email text not null unique,
  subscribed_at timestamptz not null default now()
);

create table if not exists public.visitor_events (
  id bigint generated by default as identity primary key,
  path text not null,
  visited_at timestamptz not null default now(),
  ip_address text,
  device_type text,
  browser text,
  location text,
  referrer text,
  traffic_source text
);

alter table public.students enable row level security;
alter table public.admin_profiles enable row level security;
alter table public.login_activity enable row level security;
alter table public.course_applications enable row level security;
alter table public.internship_applications enable row level security;
alter table public.career_counselling_requests enable row level security;
alter table public.contact_us enable row level security;
alter table public.newsletter_subscribers enable row level security;
alter table public.visitor_events enable row level security;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.admin_profiles admin
    where admin.id = auth.uid()
      and admin.role = 'admin'
      and admin.is_active = true
  )
  or coalesce(auth.jwt() -> 'user_metadata' ->> 'role', '') = 'admin';
$$;

create policy "students can read own profile"
on public.students for select
using (id = auth.uid() or public.is_admin());

create policy "students can insert own profile or public lead profile"
on public.students for insert
with check (id = auth.uid() or id is not null);

create policy "students can update own profile"
on public.students for update
using (id = auth.uid() or public.is_admin())
with check (id = auth.uid() or public.is_admin());

create policy "students admin delete"
on public.students for delete
using (public.is_admin());

create policy "admins manage admin profiles"
on public.admin_profiles for all
using (public.is_admin())
with check (public.is_admin());

create policy "admins can read login activity"
on public.login_activity for select
using (public.is_admin());

create policy "students can insert login activity"
on public.login_activity for insert
with check (student_id = auth.uid() or student_id is not null);

create policy "course applications insert"
on public.course_applications for insert
with check (student_id = auth.uid() or student_id is null or student_id is not null);

create policy "course applications read admin or own"
on public.course_applications for select
using (public.is_admin() or student_id = auth.uid());

create policy "course applications admin update"
on public.course_applications for update
using (public.is_admin())
with check (public.is_admin());

create policy "course applications admin delete"
on public.course_applications for delete
using (public.is_admin());

create policy "internship applications insert"
on public.internship_applications for insert
with check (student_id = auth.uid() or student_id is null or student_id is not null);

create policy "internship applications read admin or own"
on public.internship_applications for select
using (public.is_admin() or student_id = auth.uid());

create policy "internship applications admin update"
on public.internship_applications for update
using (public.is_admin())
with check (public.is_admin());

create policy "internship applications admin delete"
on public.internship_applications for delete
using (public.is_admin());

create policy "career counselling public insert"
on public.career_counselling_requests for insert
with check (true);

create policy "career counselling admin read"
on public.career_counselling_requests for select
using (public.is_admin() or student_id = auth.uid());

create policy "career counselling admin update"
on public.career_counselling_requests for update
using (public.is_admin())
with check (public.is_admin());

create policy "career counselling admin delete"
on public.career_counselling_requests for delete
using (public.is_admin());

create policy "contact public insert"
on public.contact_us for insert
with check (true);

create policy "contact admin read"
on public.contact_us for select
using (public.is_admin());

create policy "contact admin delete"
on public.contact_us for delete
using (public.is_admin());

create policy "newsletter public insert"
on public.newsletter_subscribers for insert
with check (true);

create policy "newsletter admin read"
on public.newsletter_subscribers for select
using (public.is_admin());

create policy "newsletter admin delete"
on public.newsletter_subscribers for delete
using (public.is_admin());

create policy "visitor event public insert"
on public.visitor_events for insert
with check (true);

create policy "visitor event admin read"
on public.visitor_events for select
using (public.is_admin());

create policy "visitor event admin delete"
on public.visitor_events for delete
using (public.is_admin());

-- After creating your admin user in Supabase Auth, run:
-- insert into public.admin_profiles (id, email, full_name, role)
-- values ('AUTH_USER_UUID_HERE', 'admin@jawaedtech.com', 'Jawa Admin', 'admin');
